agesMap = {
    '10- bis 19-Jährige':'age 10-19',
    '20- bis 29-Jährige':'age 20-29',
    '30- bis 39-Jährige':'age 30-39',
    '40- bis 49-Jährige':'age 40-49',
    '50- bis 59-Jährige':'age 50-59',
    '60- bis 69-Jährige':'age 60-69',
    '70- bis 79-Jährige':'age 70-79',
    '80- bis 89-Jährige':'age 80-89',
    '90- bis 99-Jährige':'age 90-99'
    }
colourMap = {'weiblich':'female',
'männlich':'male',
'albaricoque': 'red',
'apricot' : 'red',
'arena/weiss': 'sand',
'arlequín': 'spotted',
'blue': 'grey',
'blue steel': 'grey',
'blue steel': 'grey',
'blue merle/weiss': 'grey',
'blue/red': 'grey',
'beige': 'beige',
'beige gestromt': 'brindle',
'beige/braun': 'beige',
'beige/braun/schwarz': 'beige',
'beige/creme': 'beige',
'beige/grau': 'beige',
'beige/grau/weiss': 'beige',
'beige/rot': 'beige',
'beige/schwarz': 'beige',
'beige/schwarz/grau': 'beige',
'beige/weiss': 'beige',
'beige/weiss/braun': 'beige',
'bianco-aranico': 'white',
'bicolor': 'mixed',
'black/tan': 'black',
'blau': 'grey',
'blau/grau': 'grey',
'blau/grau/weiss': 'grey',
'blau/weiss': 'grey',
'blauschimmel': 'grey',
'blenheim': 'blenheim',
'blondfarben': 'golden',
'blond/weiss':'golden',
'blue fawn': 'blue grey',
'blue-brindle':'blue grey',
'blue/merle': 'blue grey',
'blue/steel': 'blue grey',
'blue/tan': 'blue grey',
'braun creme': 'brown',
'braun gefleckt': 'spotted',
'braun gestromt': 'brindle',
'braun meliert': 'brown',
'braun schimmel': 'brown',
'braun schwarz gestromt': 'brindle',
'braun': 'brown',
'braun/beige': 'brown',
'braun/gold/schwarz': 'brown',
'braun/grau': 'brown',
'braun/gold': 'brown',
'braun/rot': 'brown',
'braun/rot/weiss': 'brown',
'braun/schwarz': 'brown',
'braun/schwarz/grau': 'brown',
'braun/schwarz/weiss': 'brown',
'braun/weiss': 'brown',
'braun/weiss/beige': 'brown',
'braun/weiss/schwarz': 'brown',
'caramel': 'caramel',
'caramel/weiss': 'caramel',
'champaigne': 'champagne',
'choco': 'chocolate',
'chocolate': 'chocolate',
'chocolate/white': 'chocolate',
'chocolate/tan': 'chocolate',
'creme': 'beige',
'creme/schwarz': 'beige',
'creme':'beige',
'dapple':'brindle',
'dorado': 'golden',
'dorado/weiss': 'golden',
'dreifarbig': 'mixed',
'dunkel gestromt': 'brindle',
'dunkelbraun': 'brown',
'falb': 'sand',
'fauve': 'sand',
'fawn': 'sand',
'fox/red': 'fox red',
'foxred': 'fox red',
'gelb': 'golden',
'gelb/braun': 'golden',
'gelb/schwarz': 'golden',
'gelb/weiss': 'golden',
'gemischt': 'mixed',
'gestromt': 'brindle',
'gold gestromt/weiss': 'brindle',
'gold/sable':'golden',
'gold/schwarz': 'golden',
'gold/weiss': 'golden',
'goldbraun': 'golden',
'grau gestromt': 'brindle',
'grau meliert': 'brindle',
'grau': 'grey',
'grau/beige': 'grey',
'grau/braun': 'grey',
'grau/braun/schwarz': 'grey',
'grau/braun/weiss': 'grey',
'grau/schwarz': 'grey',
'grau/silber': 'grey',
'grau/weiss': 'grey',
'grau/weiss/beige': 'grey',
'grau/weiss/braun': 'grey',
'grau/weiss/schwarz': 'grey',
'graubraun': 'grey',
'grizzle': 'brindle',
'haarlos': 'hairless',
'harlekin': 'spotted',
'harlequin': 'spotted',
'hell-/dunkelbraun':'brown',
'hellbraun': 'brown',
'hellbraun/weiss': 'brown',
'hellfarben': 'beige',
'hígado': 'liver',
'hirschrot mit maske': 'sand',
'hirschrot': 'fox red',
'honigfarben': 'honey',
'infierno/dunkelbraun': 'brown',
'isabella': 'sand',
'lila': 'blue grey',
'lilac':'blue grey',
'löwenfarbig': 'lion',
'mahagoni': 'brown',
'mahagoni/weiss': 'brown',
'manchado': 'liver',
'marrone': 'brown',
'marronschimmel': 'brown',
'mehrfarbig': 'mixed',
'merle': 'mixed',
'moteado': 'spotted',
'naranja': 'red',
'orange':'red',
'orangeschimmel': 'red',
'oro/sable': 'golden',
'pfeffer/salz': 'brindle',
'pied': 'spotted',
'pink/chocolate':'chocolate',
'red grizzle': 'red',
'red merle':'red',
'red mirlo': 'red',
'red-fawn': 'red',
'red-schoko/merle/weiss': 'red',
'red-tri': 'red',
'red-trigo': 'red',
'red-wheaten':'red',
'rehbraun': 'sand',
'red-brindle': 'red',
'rosa/chocolate': 'chocolate',
'rot': 'red',
'rot/beige': 'red',
'rot/braun': 'red',
'rot/braun/weiss': 'red',
'rot/grau': 'red',
'rot/grau/schwarz': 'red',
'rot/schwarz': 'red',
'rot/weiss': 'red',
'rotblond': 'red',
'rotbraun / weiss / blesse': 'fox red',
'rotbraun schimmel': 'fox red',
'rotbraun': 'fox red',
'rotbraun/weiss': 'fox red',
'rotweizen': 'red',
'rubio/weiss': 'red',
'ruby': 'red',
'Sable':'fox red',
'sable': 'fox red',
'sable/white': 'fox red',
'sand/weiss':'sand',
'sandfarbig': 'sand',
'saufarben': 'red',
'schoko pied': 'chocolate',
'schoko': 'chocolate',
'schwarz gestromt': 'brindle',
'schwarz lohfarbig': 'liver',
'schwarz marken': 'black',
'schwarz melliert': 'black',
'schwarz schimmel': 'black',
'schwarz': 'black',
'schwarz/beige': 'black',
'schwarz/beige/grau': 'black',
'schwarz/braun gestromt': 'brindle',
'schwarz/braun': 'black/brown',
'schwarz/braun/beige': 'black/brown',
'schwarz/braun/grau': 'black/brown',
'schwarz/braun/rot': 'black/brown',
'schwarz/braun/weiss': 'black/brown',
'schwarz/gelb': 'black',
'schwarz/gold': 'black',
'schwarz/grau': 'black',
'schwarz/grau/weiss': 'black',
'schwarz/loh': 'liver',
'schwarz/rot': 'brindle',
'schwarz/silber': 'black/grey',
'schwarz/weiss': 'black/grey',
'schwarz/weiss/beige': 'black/grey',
'schwarz/weiss/braun': 'black/grey',
'semmelgelb': 'golden',
'silber': 'grey',
'silber/braun': 'grey',
'silber/weiss': 'grey',
'silbergrau': 'grey',
'steelblue':'blue grey',
'steelblue/tan':'blue grey',
'tigrado': 'brindle',
'tricolor': 'mixed',
'trindle': 'brindle',
'vierfarbig': 'mixed',
'weiss gestromt': 'white brindle',
'weiss schwarz zobel': 'white',
'weiss': 'white',
'weiss/apricot': 'white',
'weiss/beige': 'white',
'weiss/blau': 'white',
'weiss/braun gestromt': 'white brindle',
'weiss/braun': 'white/brown',
'weiss/braun/schwarz': 'white/brown',
'weiss/creme':'white',
'weiss/crema': 'white',
'weiss/gelb': 'white',
'weiss/grau': 'white',
'weiss/orange': 'white',
'weiss/rot': 'white',
'weiss/schwarz': 'white',
'weiss/schwarz/beige gestromt': 'white',
'weiss/schwarz/braun': 'white',
'weizen': 'sand',
'wheaton': 'sand',
'wildfarbig': 'brindle',
'wildsaufarbig': 'brindle',
'wolkig': 'grey',
'zimt': 'sand',
'zobel beige': 'beige',
'zobel': 'fox red',
'zobel/rot': 'fox red',
'zobel/weiss': 'fox red',
'zorro/rojo': 'fox red'}
breedMap = {'$Labradoodle$': 'Labradoodle',
'Affenpinscher': 'Affenpinscher',
'Afghanischer Windhund': 'Afghan Greyhound',
'Airedale Terrier': 'Airedale Terrier',
'Akita': 'Akita Inu',
'Akita Inu': 'Akita Inu',
'Alaskan Husky': 'Alaskan Husky',
'Alaskan Malamute': 'Alaskan Malamute',
'Alpenländische Dachsbracke': 'Alpine Dachsbracke',
'Altdeutscher Hütehund': 'Old German herding dog',
'Altdeutscher Schäfer': 'Old German Shepherd',
'American Akita': 'American Akita',
'American Bulldog': 'American Bulldog',
'American Cocker Spaniel': 'American Cocker Spaniel',
'American Foxhound': 'American Foxhound',
'American Staffordshire Terrier': 'American Staffordshire Terrier',
'American Water Spaniel': 'American Water Spaniel',
'Anatolischer Hirtenhund': 'Anatolian Sheepdog',
'Appenzeller': 'Appenzeller',
'Appenzeller Sennenhund': 'Appenzell Mountain dog',
'Australian Cattle Dog': 'Australian Cattle Dog',
'Australian Shepherd': 'Australian Shepherd',
'Australian Silky Terrier': 'Australian Silky Terrier',
'Australian Terrier': 'Australian Terrier',
'Australien Kelpie': 'Australia Kelpie',
'Azawakh': 'Azawakh',
'Barbet': 'barbet',
'Bardino': 'Bardino',
'Barsoi': 'borzoi',
'Basenji': 'basenji',
'Basset Fauve de Bretagne': 'Basset Fauve de Bretagne',
'Basset Hound': 'Basset Hound',
'Basset artesien normand': 'Basset artesien normand',
'Basset bleu de Gascogne': 'Basset bleu de Gascogne',
'Bayerischer Gebirgsschweisshund': 'Bavarian mountain sweathound',
'Beagle': 'Beagle',
'Bearded Collie': 'Bearded Collie',
'Beauceron': 'Beauceron',
'Beauceron Berge de Beauce': 'Beauceron Mountains de Beauce',
'Bedlington Terrier': 'Bedlington Terrier',
'Belgischer Schäferhund': 'Belgian Shepherd',
'Bergamasker': 'Bergamasque',
'Berger Picard': 'Berger de Picardie',
'Berger de Beauce': 'Berger de Beauce',
'Berger de Brie': 'Berger de Brie',
'Berger de Picardie': 'Berger de Picardie',
'Berger des Pyrenées': 'Berger des Pyrenees',
'Berner Sennenhund': 'Bernese Mountain Dog',
'Bernhardiner': 'Saint Bernard',
'Bichon': 'bichon frise',
'Bichon Havanais': 'Bichon Havanais',
'Bichon frisé': 'bichon frise',
'Bichon maltais': 'Bichon maltais',
'Bichon à poil frisé': 'Bichon frise',
'Biewer Yorkshire Terrier': 'Biewer Yorkshire Terrier',
'Bluthund': 'bloodhound',
'Bobtail (Old English Shepdog)': 'Bobtail (Old English Shepdog)',
'Boerboel': 'boerboel',
'Bologneser': 'Bolognese',
'Bolonka Zwetna': 'Bolonka Zwetna',
'Bordeauxdogge': 'Bordeaux Mastiff',
'Border': 'Border collie',
'Border Collie': 'Border Collie',
'Border Terrier': 'Border Terrier',
'Boston Terrier': 'Boston Terrier',
'Bouvier': 'bouvier',
'Bouvier des Flandres': 'Bouvier des Flanders',
'Boxer': 'Boxer',
'Bracke': 'hound',
'Brandlbracke': 'Brandlbracke',
'Braque d\x1aAuvergne': "Braque d'Auvergne",
"Braque d'Auvergne": "Braque d'Auvergne",
'Braque français (type Gascogne)': 'Braque français (type Gascogne)',
'Braquet Griffon Vendéen': 'Braquet Griffon Vendeen',
'Brasilianischer Terrier': 'Brazilian Terrier',
'Breton': 'Breton',
'Bretonischer Spaniel': 'Breton',
'Briard': 'briard',
'Briard (Berger de Brie)': 'Briard',
'Broholmer': 'broholmer',
'Bulgarischer Sennenhund': 'Bulgarian Mountain Dog',
'Bull Terrier': 'bull terrier',
'Bulldog': 'bulldog',
'Bullmastiff': 'bull mastiff',
'Ca de Bestiar (Spanischer Schäferhund)': 'Ca de Bestiar (Spanish Sheepdog)',
'Cairn Terrier': 'Cairn Terrier',
'Canaan Dog': 'Canaan Dog',
'Cane Corso': 'Cane Corso',
'Cao de Água Português': 'Cao de Água Portuguese',
'Cattle Dog': 'Cattle Dog',
'Cavalier King Charles Spaniel': 'Cavalier King Charles Spaniel',
'Cesky Fousek': 'Cesky Fousek',
'Chesapeake Bay Retriever': 'Chesapeake Bay Retriever',
'Chihuahua': 'chihuahua',
'Chinese Crested': 'Chinese Crested',
'Chinese Crested Hairless Dog': 'Chinese Crested Hairless Dog',
'Chinese Crested Powderpuff': 'Chinese Crested Powderpuff',
'Chinese Foo Dog': 'Chinese Foo Dog',
'Chodsky pes': 'Chodsky pes',
'Chow Chow': 'chow chow',
'Cimarron Uruguayo': 'Cimarron Uruguayo',
'Ciobanesc Romanesc Carpatin': 'Ciobanesc Romanesc',
'Ciobanesc Romanesc Mioritic': 'Ciobanesc Romanesc',
"Cirneco dell'Etna": "Cirneco dell'Etna",
'Cocker Spaniel': 'Cocker spaniel',
'Collie': 'border Collie',
'Continental Bulldog': 'Continental Bulldog',
'Corgie': 'corgie',
'Coton de Tulear': 'Coton de Tulear',
'Curly Coated Retriever': 'curly-coated retriever',
'Cão Fila de São Miguel': 'Cao Fila de Sao Miguel',
'Dachsbracke': 'dachshund',
'Dachshund': 'dachshund',
'Daisy-Dog': 'Daisy Dog',
'Dalmatiner': 'Dalmatian',
'Danish-Swedish Farmdog': 'Danish-Swedish Farmdog',
'Dansk/Svensk-Gardhund': 'Danish-Swedish Farmdog',
'Deerhound': 'deerhound',
'Deutsch Drahthaar': 'German Pointer',
'Deutsch Kurzhaar': 'German Pointer',
'Deutsche Bracke': 'German Pointer',
'Deutsche Dogge': 'German Mastiff',
'Deutscher Boxer': 'German Boxer',
'Deutscher Grossspitz': 'Spitz',
'Deutscher Jagdterrier': 'German Jagdterrier',
'Deutscher Kleinspitz': 'Spitz',
'Deutscher Langhaarschäfer': 'German shepherd',
'Deutscher Pinscher': 'German Pinscher',
'Deutscher Schäfer': 'German Shepherd',
'Deutscher Schäferhund': 'German shepherd',
'Deutscher Vorstehhund': 'German Pointer',
'Deutscher Wachtelhund': 'German pointer',
'Do-Khyi': 'Do-Khyi',
'Dobermann': 'doberman',
'Dogge': 'mastiff',
'Dogo Argentino': 'Dog Argentino',
'Dogo Canario': 'Dogo Canario',
'Drentse Patrijshond (Drentscher Hühnerhund)': 'Drentse Patrijshond (Drentscher Chicken Dog)',
'Elo': 'elo',
'Englische Bulldogge': 'English Bulldog',
'English Cocker Spaniel': 'English Cocker Spaniel',
'English Pointer': 'English Pointer',
'English Setter': 'English Setter',
'English Springer Spaniel': 'English Springer Spaniel',
'English Staffordshire Terrier': 'English Staffordshire Terrier',
'English Toy Terrier': 'English Toy Terrier',
'Entlebucher': 'Entlebucher',
'Entlebucher Sennenhund': 'Entlebuch Mountain Dog',
'Epagneul': 'Epagneul',
'Epagneul Breton (Bretonischer Vorstehhund)': 'Epagneul',
'Epagneul bleu de Picardie': 'Epagneul',
'Epagneul nain continental': 'Epagneul',
'Epagneul nain continental Papillon': 'Epagneul',
'Erdélyi Kopó': 'Erdélyi Kopó',
'Eurasier': 'eurasian',
'Field Spaniel': 'Field Spaniel',
'Fila Brasileiro': 'Fila Brasileiro',
'Finnischer Lapphund': 'Finnish Lapphund',
'Flat Coated Retriever': 'Flat Coated Retriever',
'Foxterrier': 'fox terrier',
'Französische Bulldogge': 'French bulldog',
'Galgo': 'Galgo Español',
'Galgo Espanol': 'Galgo Español',
'Golden Retriever': 'Golden retriever',
'Goldendoodle': 'Goldendoodle',
'Gonczy Polski': 'Gonczy Polski',
'Gordon Setter': 'Gordon Setter',
"Gos d'Atura Català": "Catalan Sheepdog (Gos d'Atura Català)",
'Grand Basset Griffon Vendeen': 'Grand Basset Griffon Vendeen',
'Grand Bleu de Gascogne': 'Grand Bleu de Gascogne',
'Grand Griffon Vendeen': 'Grand Griffon Vendeen',
'Grand anglo-français tricolore': 'Grand Anglo-Francais tricolore',
'Greyhound': 'greyhound',
'Griffon': 'Griffon',
'Griffon Fauve de Bretagne': 'Griffon Fauve de Bretagne',
'Griffon Nivernais': 'Griffon Nivernais',
'Griffon belge': 'Griffon Belge',
'Griffon bruxellois': 'Griffon belge',
'Groenendael': 'Groenendael',
'Grosser Schweizer Sennenhund': 'Greater Swiss Mountain Dog',
'Grosspudel': 'poodle',
'Grossspitz': 'Spitz',
'Havaneser': 'Havanese',
'Hirtenhund': 'sheepdog',
'Holländischer Schäfer': 'Dutch Sheepdog',
'Hovawart': 'hovawart',
'Husky': 'alaskan husky',
'Irischer rot-weiser Setter': 'Irish Setter',
'Irish Setter': 'Irish setter',
'Irish Soft Coated Wheaten Terrier': 'Irish Terrier',
'Irish Terrier': 'Irish Terrier',
'Irish Water Spaniel': 'Irish Water Spaniel',
'Irish Wolfhound': 'Irish Wolfhound',
'Islandhund': 'iceland dog',
'Istrianer Bracke': 'Istrian Hound',
'Italienische Bracke': 'Italian Hound',
'Italienisches Windspiel': 'Italian Greyhound',
'Jack Russell Terrier': 'Jack Russell terrier',
'Jagdhund': 'hound',
'Japan Chin': 'Japan Chin',
'Japan-Spitz': 'Japan-Spitz',
'Jura Laufhund': 'Jura Hound',
'Kangal': 'kangal',
'Kaninchen-Dachshund': 'dachshund',
'Katalanischer Hirtenhund': "Catalan Sheepdog (Gos d'Atura Català)",
"Katalanischer Schäferhund (Gos d'Atura Català)": "Catalan Sheepdog (Gos d'Atura Català)",
'Kaukasischer Schäfer': 'Caucasian Sheepdog',
'Kerry Blue Terrier': 'Kerry Blue Terrier',
'King Charles Spaniel': 'King Charles Spaniel',
'Kishu': 'Kishu',
'Kleiner Münsterländer': 'Small Munsterlander',
'Kleinpudel': 'poodle',
'Kleinspitz': 'Pomeranian',
'Kooikerhondje': 'Kooikerhondje',
'Korea Jindo Dog': 'Korea Jindo Dog',
'Kroatischer Schäferhund': 'Croatian Sheepdog',
'Kromfohrländer': 'Kromfohrländer',
'Kurzhaar Collie': 'border collie',
'Kurzhaar Dackel': 'Dachshund',
'Kuvasz': 'Kuvasz',
'Königspudel': 'poodle',
'Labrador': 'Labrador retriever',
'Labrador Retriever': 'Labrador Retriever',
'Lagotto Romagnolo': 'Lagotto Romagnolo',
'Laika': 'Laika',
'Lakeland Terrier': 'Lakeland Terrier',
'Landseer': 'Landseer',
'Langhaardackel': 'dachshund',
'Lemon Walker Hound': 'Lemon Walker Hound',
'Leonberger': 'Leonberger',
'Lhasa Apso': 'Lhasa Apso',
'Luzerner Laufhund': 'Lucerne Hound',
'Luzerner Niederlaufhund': 'Lucerne low-running dog',
'Löwchen': 'lion',
'Magyar Viszla': 'Viszla',
'Malamut': 'malamut',
'Malinois': 'Malinois',
'Malteser': 'Maltese',
'Manchester Terrier': 'Manchester Terrier',
'Maremmano': 'Maremma',
'Maremmen-Abruzzen-Schäferhund': 'Maremma-Abruzzo Sheepdog',
'Mastiff': 'mastiff',
'Mastino Napoletano': 'Napoletano Mastiff',
'Mexikanischer Nackthund': 'Mexican Hairless Dog',
'Miniature American Shepard': 'Miniature American Shepherd',
'Miniature Australian Shepherd': 'Miniature Australian Shepherd',
'Miniature Bull Terrier': 'Miniature Bull Terrier',
'Minipudel': 'poodle',
'Mischling': 'mongrel',
'Mittelpudel': 'poodle',
'Mittelschnauzer': 'schnauzer',
 'Mittelspitz': 'spitz',
'Montenegrinischer Gebirgslaufhund': 'Montenegrin Mountain Hound',
'Mops': 'Pug',
'Mudi': 'mud',
'Münsterländer': 'Muensterlander',
'Neufundländer': 'Newfoundland',
'Niederlaufhund': 'downhill dog',
'Nihon Supittsu': 'Nihon Supittsu',
'Norfolk Terrier': 'Norfolk Terrier',
'Norwegischer Buhund': 'Norwegian',
'Norwegischer Lundehund': 'Norwegian',
'Norwich Terrier': 'Norwich Terrier',
'Nova Scotia Duck Tolling Retriever': 'Nova Scotia Duck Tolling Retriever',
'Oesterreichischer Pinscher': 'Austrian Pinscher',
'Old Englische Bulldogge': 'Old English Bulldog',
'Old English  Sheepdog': 'Old English Sheepdog',
'Papillon': 'papillon',
'Parson Jack Russell Terrier': 'Jack Russell Terrier',
'Parson Russell Terrier': 'Parson Terrier',
'Parson Terrier': 'Parson Terrier',
'Pekingese': 'Pekingese',
'Perro Dogo Mallorquin': 'Perro Dogo Mallorquin',
'Perro Sin Pelo Del Perú klein': 'Perro Sin Pelo Del Perú small',
'Perro de Agua Espanol': 'Perro de Agua Espanol',
'Petit Basset Griffon Vendéen': 'Petit Basset Griffon Vendeen',
'Petit Brabançon': 'Petit Brabancon',
'Phalène': 'Phalene',
'Pharaonenhund': 'pharaoh hound',
'Pinscher': 'Pinscher',
'Pit Bull Terrier': 'pit bull terrier',
'Podenco': 'podenco',
'Podenco Canario': 'Podenco Canario',
'Podenco Ibicenco': 'Podenco Ibicenco',
'Podengo Portugues': 'Portuguese Podengo',
'Podengo Portugues klein': 'Podengo Portuguese small',
'Pointer': 'Pointer',
'Poitevin': 'Poitevin',
'Polnische Bracke': 'Polish Hound',
'Polnischer Niederungshütehund': 'Polish Lowland Sheepdog',
'Pomeranian': 'Pomeranian',
'Portugiesicher Vorstehhund': 'Portuguese Pointer',
'Portugiesischer Schäferhund': 'Portuguese Shepherd',
'Portugiesischer Wasserhund': 'Portuguese Water Dog',
'Powder Puff': 'powder puff',
'Prager Rattler': 'Prague Ratter',
'Pudel': 'Poodle',
'Pudelpointer': 'poodle',
'Puli': 'Puli',
'Pumi': 'Pumi',
'Pyrenäenberghund': 'Pyrenean Mountain Dog',
'Ratenero Bodeguero': 'Ratenero Bodeguero',
'Ratero': 'Ratero',
'Rauhaar Dackel': 'wire-haired dachshund',
'Rehpinscher': 'deer pinscher',
'Retriever': 'Retriever',
'Rhodesian Ridgeback': 'Rhodesian Ridgeback',
'Riesenschnauzer': 'giant schnauzer',
'Rottweiler': 'Rottweiler',
'Russischer Toy': 'Russian Toy',
'Russischer schwarzer Terrier': 'Russian Black Terrier',
'Saarloos-Wolfshund': 'Saarloos Wolfhound',
'Saluki': 'Saluki',
'Samojede': 'Samoyed',
'Schapendoes': 'Schapendoes',
'Schipperke': 'Schipperke',
'Schnauzer': 'Schnauzer',
'Schwedischer Vallhund': 'Swedish Vallhund',
'Schweizer Laufhund': 'Swiss Hound',
'Schweizer Niederlaufhund': 'Schwyzer Niederlaufhund',
'Schweizer Sennenhund': 'Swiss Mountain Dog',
'Schwyzer Niederlaufhund': 'Schwyzer Niederlaufhund',
'Schäfer': 'Sheepdog',
'Scottish Terrier': 'Scottish Terrier',
'Segugio italiano': 'Segugio Italiano',
'Sennenhund': 'mountain dog',
'Setter': 'Setter',
'Shar Pei': 'Shar Pei',
'Sheltie': 'shelties',
'Shetland Sheepdog': 'Shetland Sheepdog',
'Shiba Inu': 'Shiba Inu',
'Shih Tzu': 'shih tzu',
'Shikoku': 'shikoku',
'Siberian Husky': 'Siberian Husky',
'Sibirischer Husky': 'Siberian Husky',
'Silky Terrier': 'silky terrier',
'Skye Terrier': 'Skye Terrier',
'Sloughi': 'Sloughi',
'Slovensky Cuvac': 'Slovensky Cuvac',
'Soft Coated Wheaten Terrier': 'Soft Coated Wheaten Terrier',
'Spaniel': 'Spaniel',
'Spanischer Laufhund (Sabueso Espanol)': 'Spanish Hound (Sabueso Espanol)',
'Spanischer Wasserhund': 'Spanish Water Dog',
'Spanischer Windhund': 'Spanish Greyhound',
'Spinone': 'spinons',
'Spitz': 'spitz',
'St. Bernhardshund - Bernhardiner': 'St. Bernard',
'Stabijhoun': 'Stabihoun',
'Staffordshire Bullterrier': 'Staffordshire Bull Terrier',
'Taiwanhund': 'Taiwan Dog',
'Tamaskan': 'Tamaskan',
'Teckel': 'dachshund',
'Terrier': 'Terrier',
'Tervueren': 'Tervueren',
'Thai Ridgeback': 'Thai Ridgeback',
'Tibet Terrier': 'Tibet terrier',
'Tibetan Spaniel': 'Tibetan Spaniel',
'Tiroler Bracke': 'Tyrolean Hound',
'Toller': 'great dane',
'Tosa Inu': 'Tosa Inu',
'Toy Pudel': 'Toy Poodle',
'Toypudel': 'toy poodle',
'Toyterrier': 'toy terrier',
'Transylvanischer Laufhund': 'Transylvanian Hound',
'Tschechischer Terrier': 'Czech Terrier',
'Tschechoslowakischer Wolfshund': 'Czechoslovakian Wolfhound',
'Unbekannt': 'Unknown',
'Vizsla': 'Vizsla',
'Volpino Italiano': 'Volpino Italiano',
'Vorstehhund': 'Pointer',
'Västgötaspets (Westgotenspitz)': 'Spitz',
'Wasserhund': 'Water Dog',
'Weimaraner': 'Weimaraner',
'Weisser Schäferhund (Berger Blanc Suisse)': 'White German Shepherd (Berger Blanc Suisse)',
'Welsh Corgi': 'Welsh Corgi',
'Welsh Corgi Cardigan': 'Welsh Corgi',
'Welsh Corgi Pembroke': 'Welsh Corgi',
'Welsh Springer Spaniel': 'Welsh Springer Spaniel',
'Welsh Terrier': 'Welsh Terrier',
'West Highland White Terrier': 'West Highland White Terrier',
'Westgotenspitz': 'Spitz',
'Whippet': 'Whippet',
'Windhund': 'Greyhound',
'Windspiel': 'Greyhound',
'Wolfspitz': 'Wolfhound',
'Wäller': 'Waller',
'Xoloitzcuintle': 'Xoloitzcuintle',
'Yorkshire Terrier': 'Yorkshire Terrier',
'Zwergdachshund': 'dachshund',
'Zwergdackel': 'dachshund',
'Zwergpinscher': 'miniature pinscher',
'Zwergpudel': 'toy poodle',
'Zwergrauhaardackel': 'Dachshund',
'Zwergschnauzer': 'Schnauzer',
'Zwergspitz': 'Pomeranian'}